CREATE DATABASE supply_chain;
USE supply_chain;

CREATE TABLE supply_chain_data (
    product_type VARCHAR(50),
    sku VARCHAR(20),
    price DECIMAL(10,2),
    availability INT,
    products_sold INT,
    revenue DECIMAL(10,2),
    customer_demographics VARCHAR(50),
    stock_levels INT,
    lead_times INT,
    order_quantities INT,
    shipping_times INT,
    shipping_carriers VARCHAR(50),
    shipping_costs DECIMAL(10,2),
    supplier_name VARCHAR(100),
    location VARCHAR(100),
    lead_time INT,
    production_volumes INT,
    manufacturing_lead_time INT,
    manufacturing_costs DECIMAL(10,2),
    inspection_results VARCHAR(50),
    defect_rates DECIMAL(5,2),
    transportation_modes VARCHAR(50),
    routes VARCHAR(50),
    costs DECIMAL(10,2)
);
SELECT COUNT(*) AS total_records FROM supply_chain_data;

SELECT * FROM supply_chain_data;

-- Query 1: Top 5 Highest Revenue Products
SELECT sku,product_type,revenue FROM supply_chain_data
ORDER BY revenue DESC
LIMIT 5;

-- Query 2: Revenue by Product Type
SELECT product_type,
       ROUND(SUM(revenue),2) AS total_revenue
FROM supply_chain_data
GROUP BY product_type
ORDER BY total_revenue DESC;

-- Query 3: Average Shipping Cost by Carrier
SELECT shipping_carriers,
       ROUND(AVG(shipping_costs),2) AS avg_shipping_cost
FROM supply_chain_data
GROUP BY shipping_carriers
ORDER BY avg_shipping_cost DESC;

-- Query 4: Top Supplier by Products Sold
SELECT 
    supplier_name, SUM(products_sold) AS total_products_sold
FROM
    supply_chain_data
GROUP BY supplier_name
ORDER BY total_products_sold DESC;

-- Query 5: Find total revenue generated by each location

SELECT
    location,
    SUM(revenue) AS total_revenue
FROM supply_chain_data
GROUP BY location
ORDER BY total_revenue DESC;

-- Query 6: Products with High Defect Rate
SELECT sku,
       product_type,
       defect_rates
FROM supply_chain_data
WHERE defect_rates > 3
ORDER BY defect_rates DESC;

-- Query 7: Passed Quality Inspection
SELECT *
FROM supply_chain_data
WHERE inspection_results='Pass';

-- Query 8: Supplier Performance
SELECT supplier_name,
       COUNT(*) AS total_products,
       ROUND(AVG(defect_rates),2) AS avg_defect_rate,
       ROUND(SUM(revenue),2) AS total_revenue
FROM supply_chain_data
GROUP BY supplier_name
ORDER BY total_revenue DESC;

-- Query 9 – Above Average Revenue 
SELECT sku,
       product_type,
       revenue
FROM supply_chain_data
WHERE revenue > (
    SELECT AVG(revenue)
    FROM supply_chain_data
)
ORDER BY revenue DESC;
-- Query 10 –Stock Status 
SELECT
    sku,
    stock_levels,
    CASE
    WHEN stock_levels >= 70 THEN 'High Stock'
    WHEN stock_levels >= 30 THEN 'Medium Stock'
    ELSE 'Low Stock'
END AS stock_status
FROM supply_chain_data;

-- Query 11 – Revenue Ranking (Window Function)
SELECT
    sku,
    revenue,
    RANK() OVER (ORDER BY revenue DESC) AS revenue_rank
FROM supply_chain_data;

-- Query 12 – Create View
CREATE VIEW supplier_revenue AS
SELECT
    supplier_name,
    SUM(revenue) AS total_revenue
FROM supply_chain_data
GROUP BY supplier_name;

select * from supplier_revenue;
